name: 'Terraform Deploy'

on:
  workflow_call: 
    
permissions:
  contents: read

jobs:

  deploy:
    name: 'Deploy infrastructure'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init -upgrade

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -var user_pool_name="${{ vars.BMB_USER_POOL_NAME }}"
