name: 'Terraform'

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual deploy"
        default: "Manual deploy"

permissions:
  contents: read

jobs:

  test:
    name: 'Test'
    runs-on: ubuntu-latest
    environment: uat

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init -upgrade

    - name: Terraform Test
      if: github.event_name == 'push'
      run: terraform test

  sonarcloud:
    needs: [test]
    if: github.event_name != 'pull_request' || github.ref == 'refs/heads/main'
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  create-infrastructure:
    
    needs: [test]
    if: github.event_name != 'pull_request' || github.ref == 'refs/heads/main'
    name: 'Plan'
    runs-on: ubuntu-latest
    environment: uat
    env:
      TF_VAR_user_pool_name: "${{ vars.BMB_USER_POOL_NAME }}"

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init -upgrade

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -var user_pool_name="${{ env.BMB_USER_POOL_NAME }}"
